"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_bootstrap_1 = require("react-bootstrap");
var React = require("react");
var MainPage = /** @class */ (function (_super) {
    tslib_1.__extends(MainPage, _super);
    function MainPage(props, context) {
        var _this = _super.call(this, props, context) || this;
        _this.handleSelect = _this.handleSelect.bind(_this);
        _this.state = {
            key: 1
        };
        return _this;
    }
    MainPage.prototype.handleSelect = function (key) {
        this.setState({ key: key });
    };
    MainPage.prototype.render = function () {
        return React.createElement("div", { className: "mainpage-body" },
            React.createElement("img", { src: "/static/logo_white.png", className: "whitelogo" }),
            React.createElement("h2", { className: "developer" }, "CC98\u7F16\u7A0B\u6280\u672F\u7248"),
            React.createElement("h2", { className: "database" }, "\u6570\u636E\u5E93\u6280\u672F"),
            React.createElement("img", { src: "./static/logo.png", className: "logo" }),
            React.createElement("div", { style: { marginTop: "-20px" } },
                React.createElement("img", { src: "/static/blockchain.jpg", width: "1515px" }),
                React.createElement("h1", { className: "title" }, "\u6D59\u6C5F\u5927\u5B66\u56FE\u4E66\u7BA1\u7406\u7CFB\u7EDF"),
                React.createElement("h2", { className: "title1" }, "\u81F4\u529B\u4E8E\u4E3A\u6D59\u5927\u5E08\u751F\u63D0\u4F9B\u4E00\u4E2A\u4FBF\u643A\u7684\u56FE\u4E66\u501F\u9605\u89E3\u51B3\u65B9\u6848")),
            React.createElement("div", { style: { width: "900px", marginTop: "230px" } },
                React.createElement(react_bootstrap_1.Tabs, { activeKey: this.state.key, onSelect: this.handleSelect, id: "controlled-tab-example" },
                    React.createElement(react_bootstrap_1.Tab, { eventKey: 1, title: "科幻" },
                        React.createElement(react_bootstrap_1.Table, { striped: true, bordered: true, condensed: true, hover: true },
                            React.createElement("thead", null,
                                React.createElement("tr", null,
                                    React.createElement("th", null, "\u4E66\u540D"),
                                    React.createElement("th", null, "\u4F5C\u8005"),
                                    React.createElement("th", null, "\u51FA\u7248\u793E"),
                                    React.createElement("th", null, "\u5E74\u4EFD"),
                                    React.createElement("th", null, "\u4EF7\u683C"),
                                    React.createElement("th", null, "\u5E93\u5B58"),
                                    React.createElement("th", null, "\u603B\u91CF"))),
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E09\u4F53"),
                                    React.createElement("td", null, "\u5218\u6148\u6B23"),
                                    React.createElement("td", null, "\u91CD\u5E86\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "2005"),
                                    React.createElement("td", null, "33.00"),
                                    React.createElement("td", null, "12"),
                                    React.createElement("td", null, "20")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u94F6\u6CB3\u5E1D\u56FD\uFF1A\u57FA\u5730"),
                                    React.createElement("td", null, "\u963F\u897F\u83AB\u592B"),
                                    React.createElement("td", null, "\u6C5F\u82CF\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1940"),
                                    React.createElement("td", null, "41.00"),
                                    React.createElement("td", null, "2"),
                                    React.createElement("td", null, "10")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6C99\u4E18"),
                                    React.createElement("td", null, "\u5F17\u5170\u514B\u30FB\u8D6B\u4F2F\u7279 "),
                                    React.createElement("td", null, "\u6C5F\u82CF\u51E4\u51F0\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1950"),
                                    React.createElement("td", null, "66.00"),
                                    React.createElement("td", null, "4"),
                                    React.createElement("td", null, "5")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E07\u6709\u5F15\u529B\u4E4B\u8679"),
                                    React.createElement("td", null, "\u6258\u9A6C\u65AF\u30FB\u54C1\u94A6"),
                                    React.createElement("td", null, "\u8BD1\u6797\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1973"),
                                    React.createElement("td", null, "53.00"),
                                    React.createElement("td", null, "7"),
                                    React.createElement("td", null, "8")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6F2B\u957F\u7684\u660E\u5929"),
                                    React.createElement("td", null, "\u96F7\u30FB\u5E03\u62C9\u51EF\u7279 "),
                                    React.createElement("td", null, "\u6F13\u6C5F\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1955"),
                                    React.createElement("td", null, "43.00"),
                                    React.createElement("td", null, "0"),
                                    React.createElement("td", null, "2"))))),
                    React.createElement(react_bootstrap_1.Tab, { eventKey: 2, title: "历史" },
                        React.createElement(react_bootstrap_1.Table, { striped: true, bordered: true, condensed: true, hover: true },
                            React.createElement("thead", null,
                                React.createElement("tr", null,
                                    React.createElement("th", null, "\u4E66\u540D"),
                                    React.createElement("th", null, "\u4F5C\u8005"),
                                    React.createElement("th", null, "\u51FA\u7248\u793E"),
                                    React.createElement("th", null, "\u5E74\u4EFD"),
                                    React.createElement("th", null, "\u4EF7\u683C"),
                                    React.createElement("th", null, "\u5E93\u5B58"),
                                    React.createElement("th", null, "\u603B\u91CF"))),
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E09\u4F53"),
                                    React.createElement("td", null, "\u5218\u6148\u6B23"),
                                    React.createElement("td", null, "\u91CD\u5E86\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "2005"),
                                    React.createElement("td", null, "33.00"),
                                    React.createElement("td", null, "12"),
                                    React.createElement("td", null, "20")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u94F6\u6CB3\u5E1D\u56FD\uFF1A\u57FA\u5730"),
                                    React.createElement("td", null, "\u963F\u897F\u83AB\u592B"),
                                    React.createElement("td", null, "\u6C5F\u82CF\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1940"),
                                    React.createElement("td", null, "41.00"),
                                    React.createElement("td", null, "2"),
                                    React.createElement("td", null, "10")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6C99\u4E18"),
                                    React.createElement("td", null, "\u5F17\u5170\u514B\u30FB\u8D6B\u4F2F\u7279 "),
                                    React.createElement("td", null, "\u6C5F\u82CF\u51E4\u51F0\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1950"),
                                    React.createElement("td", null, "66.00"),
                                    React.createElement("td", null, "4"),
                                    React.createElement("td", null, "5")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E07\u6709\u5F15\u529B\u4E4B\u8679"),
                                    React.createElement("td", null, "\u6258\u9A6C\u65AF\u30FB\u54C1\u94A6"),
                                    React.createElement("td", null, "\u8BD1\u6797\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1973"),
                                    React.createElement("td", null, "53.00"),
                                    React.createElement("td", null, "7"),
                                    React.createElement("td", null, "8")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6F2B\u957F\u7684\u660E\u5929"),
                                    React.createElement("td", null, "\u96F7\u30FB\u5E03\u62C9\u51EF\u7279 "),
                                    React.createElement("td", null, "\u6F13\u6C5F\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1955"),
                                    React.createElement("td", null, "43.00"),
                                    React.createElement("td", null, "0"),
                                    React.createElement("td", null, "2"))))),
                    React.createElement(react_bootstrap_1.Tab, { eventKey: 3, title: "计算机" },
                        React.createElement(react_bootstrap_1.Table, { striped: true, bordered: true, condensed: true, hover: true },
                            React.createElement("thead", null,
                                React.createElement("tr", null,
                                    React.createElement("th", null, "\u4E66\u540D"),
                                    React.createElement("th", null, "\u4F5C\u8005"),
                                    React.createElement("th", null, "\u51FA\u7248\u793E"),
                                    React.createElement("th", null, "\u5E74\u4EFD"),
                                    React.createElement("th", null, "\u4EF7\u683C"),
                                    React.createElement("th", null, "\u5E93\u5B58"),
                                    React.createElement("th", null, "\u603B\u91CF"))),
                            React.createElement("tbody", null,
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E09\u4F53"),
                                    React.createElement("td", null, "\u5218\u6148\u6B23"),
                                    React.createElement("td", null, "\u91CD\u5E86\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "2005"),
                                    React.createElement("td", null, "33.00"),
                                    React.createElement("td", null, "12"),
                                    React.createElement("td", null, "20")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u94F6\u6CB3\u5E1D\u56FD\uFF1A\u57FA\u5730"),
                                    React.createElement("td", null, "\u963F\u897F\u83AB\u592B"),
                                    React.createElement("td", null, "\u6C5F\u82CF\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1940"),
                                    React.createElement("td", null, "41.00"),
                                    React.createElement("td", null, "2"),
                                    React.createElement("td", null, "10")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6C99\u4E18"),
                                    React.createElement("td", null, "\u5F17\u5170\u514B\u30FB\u8D6B\u4F2F\u7279 "),
                                    React.createElement("td", null, "\u6C5F\u82CF\u51E4\u51F0\u6587\u827A\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1950"),
                                    React.createElement("td", null, "66.00"),
                                    React.createElement("td", null, "4"),
                                    React.createElement("td", null, "5")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u4E07\u6709\u5F15\u529B\u4E4B\u8679"),
                                    React.createElement("td", null, "\u6258\u9A6C\u65AF\u30FB\u54C1\u94A6"),
                                    React.createElement("td", null, "\u8BD1\u6797\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1973"),
                                    React.createElement("td", null, "53.00"),
                                    React.createElement("td", null, "7"),
                                    React.createElement("td", null, "8")),
                                React.createElement("tr", null,
                                    React.createElement("td", null, "\u6F2B\u957F\u7684\u660E\u5929"),
                                    React.createElement("td", null, "\u96F7\u30FB\u5E03\u62C9\u51EF\u7279 "),
                                    React.createElement("td", null, "\u6F13\u6C5F\u51FA\u7248\u793E"),
                                    React.createElement("td", null, "1955"),
                                    React.createElement("td", null, "43.00"),
                                    React.createElement("td", null, "0"),
                                    React.createElement("td", null, "2"))))))));
    };
    return MainPage;
}(React.Component));
exports.MainPage = MainPage;
